name: dartboard
description: A collection of boilerplate snippets in Dart.
version: 0.0.1
author: asherbar <asherbare@gmail.com>
homepage: https://github.com/asherbar/dartboard

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
